apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  SPRING_APPLICATION_NAME: "student-management"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SERVER_PORT: "8089"
  SERVER_SERVLET_CONTEXT_PATH: "/student"
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: ""
